services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:6.7-php8.2-apache
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: "1"
      WORDPRESS_CONFIG_EXTRA: "define('WPLANG', 'fi');"
    volumes:
      - wp_data:/var/www/html
      - /home/santeri-leinonen/Documents/Ohjelmointiprojektit/Vihreät/UUVI verkkosivut /uudenmaan-vihreat-theme:/var/www/html/wp-content/themes/uudenmaan-vihreat-theme

volumes:
  db_data:
  wp_data:
